import type { Content, User, FeaturedTemplate, Comment } from '../types';

export const mockUser: User = {
  id: 'u_001',
  email: 'cat@vibepop.app',
  username: 'catmaster',
  displayName: '猫主人',
  avatar: '😺',
  bio: '用AI创造好玩的东西 🎮✨',
  followingCount: 123,
  followersCount: 456,
  createdAt: '2026-03-01T00:00:00Z',
};

const gradients = [
  'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
  'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
  'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
  'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)',
  'linear-gradient(135deg, #fa709a 0%, #fee140 100%)',
  'linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)',
];

export const mockContents: Content[] = [
  {
    id: 'cnt_001',
    title: '弹球挑战',
    description: '用脸当球试试？',
    type: 'game',
    code: '<div style="display:flex;align-items:center;justify-content:center;height:100%;font-size:72px">🎮</div>',
    coverUrl: '',
    coverEmoji: '🎮',
    coverGradient: gradients[0],
    tags: ['弹球', 'AI生成'],
    authorId: 'u_002',
    author: { id: 'u_002', username: 'xiaoming', displayName: '小明的创意工坊', avatar: '🎨' },
    status: 'published',
    playCount: 12500,
    likeCount: 1200,
    favoriteCount: 345,
    commentCount: 89,
    remixCount: 23,
    createdAt: '2026-04-01T00:00:00Z',
    publishedAt: '2026-04-01T00:00:00Z',
  },
  {
    id: 'cnt_002',
    title: '大理之旅',
    description: '风花雪月',
    type: 'album',
    code: '<div style="display:flex;align-items:center;justify-content:center;height:100%;font-size:72px">📸</div>',
    coverUrl: '',
    coverEmoji: '📸',
    coverGradient: gradients[1],
    tags: ['旅行', '相册'],
    authorId: 'u_003',
    author: { id: 'u_003', username: 'travel', displayName: '旅行日记', avatar: '✈️' },
    status: 'published',
    playCount: 8900,
    likeCount: 2300,
    favoriteCount: 567,
    commentCount: 156,
    remixCount: 12,
    createdAt: '2026-04-02T00:00:00Z',
    publishedAt: '2026-04-02T00:00:00Z',
  },
  {
    id: 'cnt_003',
    title: '毒舌点评',
    description: '看图说话',
    type: 'tool',
    code: '<div style="display:flex;align-items:center;justify-content:center;height:100%;font-size:72px">🎨</div>',
    coverUrl: '',
    coverEmoji: '🎨',
    coverGradient: gradients[2],
    tags: ['AI', '搞笑'],
    authorId: 'u_004',
    author: { id: 'u_004', username: 'dushe', displayName: '毒舌AI', avatar: '🤖' },
    status: 'published',
    playCount: 25600,
    likeCount: 5600,
    favoriteCount: 1200,
    commentCount: 892,
    remixCount: 56,
    createdAt: '2026-04-03T00:00:00Z',
    publishedAt: '2026-04-03T00:00:00Z',
  },
  {
    id: 'cnt_004',
    title: '时光相册',
    description: '记录美好时光',
    type: 'album',
    code: '<div style="display:flex;align-items:center;justify-content:center;height:100%;font-size:72px">⏰</div>',
    coverUrl: '',
    coverEmoji: '⏰',
    coverGradient: gradients[3],
    tags: ['相册', '回忆'],
    authorId: 'u_005',
    author: { id: 'u_005', username: 'timemachine', displayName: '时光机', avatar: '⏰' },
    status: 'published',
    playCount: 432,
    likeCount: 98,
    favoriteCount: 45,
    commentCount: 23,
    remixCount: 5,
    createdAt: '2026-04-04T00:00:00Z',
    publishedAt: '2026-04-04T00:00:00Z',
  },
  {
    id: 'cnt_005',
    title: '躲避障碍',
    description: '看看你能活多久',
    type: 'game',
    code: '<div style="display:flex;align-items:center;justify-content:center;height:100%;font-size:72px">🎯</div>',
    coverUrl: '',
    coverEmoji: '🎯',
    coverGradient: gradients[4],
    tags: ['游戏', '挑战'],
    authorId: 'u_002',
    author: { id: 'u_002', username: 'xiaoming', displayName: '小明的创意工坊', avatar: '🎨' },
    status: 'published',
    playCount: 3400,
    likeCount: 892,
    favoriteCount: 234,
    commentCount: 67,
    remixCount: 18,
    createdAt: '2026-04-05T00:00:00Z',
    publishedAt: '2026-04-05T00:00:00Z',
  },
  {
    id: 'cnt_006',
    title: '生日贺卡',
    description: '送给最爱的人',
    type: 'other',
    code: '<div style="display:flex;align-items:center;justify-content:center;height:100%;font-size:72px">🎂</div>',
    coverUrl: '',
    coverEmoji: '🎂',
    coverGradient: gradients[5],
    tags: ['贺卡', '生日'],
    authorId: 'u_006',
    author: { id: 'u_006', username: 'cardmaker', displayName: '贺卡工厂', avatar: '🎂' },
    status: 'published',
    playCount: 1800,
    likeCount: 445,
    favoriteCount: 189,
    commentCount: 56,
    remixCount: 34,
    createdAt: '2026-04-06T00:00:00Z',
    publishedAt: '2026-04-06T00:00:00Z',
  },
];

export const mockMyContents: Content[] = [
  {
    ...mockContents[0],
    id: 'cnt_my_001',
    title: '我的弹球',
    authorId: 'u_001',
    author: { id: 'u_001', username: 'catmaster', displayName: '猫主人', avatar: '😺' },
    playCount: 523,
    likeCount: 67,
  },
  {
    ...mockContents[5],
    id: 'cnt_my_002',
    title: '妈妈生日',
    authorId: 'u_001',
    author: { id: 'u_001', username: 'catmaster', displayName: '猫主人', avatar: '😺' },
    playCount: 1200,
    likeCount: 234,
  },
];

export const mockTemplates: FeaturedTemplate[] = [
  { id: 'tmpl_001', title: '弹球游戏', emoji: '🎮', gradient: gradients[0], prompt: '做一个弹球打砖块小游戏，点击发射小球，击中得分。', sortOrder: 1, isActive: true },
  { id: 'tmpl_002', title: '旅行相册', emoji: '📸', gradient: gradients[1], prompt: '做一个可左右滑动的旅行相册，每张卡片一张风景图和文案。', sortOrder: 2, isActive: true },
  { id: 'tmpl_003', title: '生日贺卡', emoji: '🎂', gradient: gradients[4], prompt: '做一个动态生日贺卡，蛋糕跳动，点击有烟花动画。', sortOrder: 3, isActive: true },
  { id: 'tmpl_004', title: '躲避障碍', emoji: '🎯', gradient: gradients[2], prompt: '做一个躲避障碍小游戏，方块从上方下落，底部角色左右躲避。', sortOrder: 4, isActive: true },
];

export const mockComments: Comment[] = [
  { id: 'cmt_001', contentId: 'cnt_001', userId: 'u_003', user: { id: 'u_003', username: 'travel', displayName: '旅行日记', avatar: '✈️' }, text: '太好玩了！', createdAt: '2026-04-07T10:00:00Z' },
  { id: 'cmt_002', contentId: 'cnt_001', userId: 'u_004', user: { id: 'u_004', username: 'dushe', displayName: '毒舌AI', avatar: '🤖' }, text: '哈哈哈用脸当球笑死我了', createdAt: '2026-04-07T11:00:00Z' },
  { id: 'cmt_003', contentId: 'cnt_001', userId: 'u_005', user: { id: 'u_005', username: 'timemachine', displayName: '时光机', avatar: '⏰' }, text: '我也想做一个！怎么 Remix？', createdAt: '2026-04-07T12:00:00Z' },
];

export function formatCount(num: number): string {
  if (num >= 10000) return (num / 10000).toFixed(1) + 'w';
  if (num >= 1000) return (num / 1000).toFixed(1) + 'k';
  return num.toString();
}
